django-app-working-with-modal-forms/django_project/modal/urls.py
from django.urls import path

from . import views


app_name = 'modal'
urlpatterns = [
	path('', views.EmployeeListView.as_view(), name='home'),
	path('create/', views.CreateEmployeeView.as_view(), name='create'),
	path('update/<int:pk>/', views.UpdateEmployeeView.as_view(), name='update'),
	path('delete/<int:pk>/', views.DeleteEmployeeView.as_view(), name='delete'),

]

django-app-working-with-modal-forms/django_project/modal/models.py
from django.db import models

class Employee(models.Model):
	first_name 	= models.CharField(max_length=30)
	last_name 	= models.CharField(max_length=30)
	full_name 	= models.CharField(max_length=60, blank=True)
	email		= models.EmailField(max_length=30)

	def __str__(self):
		return self.first_name

	def save(self, *args, **kwargs):
		self.full_name = '{0} {1}'.format(self.first_name, self.last_name)
		super(Employee, self).save(*args, **kwargs)

django-app-working-with-modal-forms/django_project/modal/forms.py
from django import forms


from .models import Employee


class EmployeeForm(forms.ModelForm):
	class Meta:
		model = Employee
		fields = ['first_name', 'last_name', 'email']

django-app-working-with-modal-forms/django_project/modal/views.py
from django.views import generic
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import edit


from .models import Employee
from .mixins import ModelMixin
from .forms import EmployeeForm
from .ajax_views import (AjaxCreateView, AjaxDetailView, AjaxUpdateView, AjaxDeleteView)


class EmployeeListView(ModelMixin, generic.ListView):
	model = Employee
	template_name = 'modal/home.html'


class CreateEmployeeView(AjaxCreateView, ModelMixin, edit.CreateView):
	model = Employee
	form_class = EmployeeForm
	ajax_partial = 'modal/partial/employee_form_partial.html'
	ajax_list_partial = 'modal/partial/employee_list_partial.html'


class UpdateEmployeeView(AjaxUpdateView, ModelMixin, edit.UpdateView):
	model = Employee
	form_class = EmployeeForm
	template_name = 'modal/employee_form.html'
	ajax_partial = 'modal/partial/employee_form_partial.html'
	ajax_list_partial = 'modal/partial/employee_list_partial.html'


class DeleteEmployeeView(AjaxDeleteView, ModelMixin, edit.DeleteView):
	model = Employee
	ajax_partial = 'modal/partial/employee_form_partial.html'
	ajax_list_partial = 'modal/partial/employee_list_partial.html'
	success_url = reverse_lazy('modal:home')

django-app-working-with-modal-forms/django_project/modal/templates/modal/create.html
{% extends 'base.html' %}


{% block content %}
	<form method="post">{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Add">
	</form>
{% endblock %}

django-app-working-with-modal-forms/django_project/modal/templates/modal/delete.html
{% extends 'base.html' %}


{% block content %}
	<p><strong>Are you sure you want to delete this "{{object}}"?</strong></p>
	<form method="post">{% csrf_token %}
		{{form.as_p}}
		<a href="{% url 'modal:home' %}">Cancel</a>
		<input type="submit" value="Delete">
	</form>
{% endblock %}

django-app-working-with-modal-forms/django_project/modal/templates/modal/home.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
        <div class="table-wrapper">
            
            {% include 'modal/snippets/table-title.html' %}

            <table class="table table-striped table-hover">
                <thead>
                    <tr>
						<th>{% include 'modal/snippets/custom-checkbox-header.html' %}</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for employee in object_list %}
                    <tr>
						<td>{% include 'modal/snippets/custom-checkbox-body.html' %}</td>
                        <td>{{employee.full_name}}</td>
                        <td>{{employee.email}}</td>
                        <td>{% include 'modal/snippets/actions.html' %}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            {% include 'modal/snippets/modal-add.html' %}
            {% include 'modal/snippets/modal-edit.html' %}
            {% include 'modal/snippets/modal-delete.html' %}
        </div>
    </div>
{% endblock %}

django-app-working-with-modal-forms/django_project/modal/templates/modal/snippets/actions.html
<a href="#editEmployeeModal" class="edit" data-toggle="modal">
	<i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i>
</a>
<a href="{% url 'modal:delete' employee.id %}" class="delete">
	<i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i>
</a>

django-app-working-with-modal-forms/django_project/modal/templates/modal/snippets/custom-checkbox-body.html
<span class="custom-checkbox">
	<input type="checkbox" id="checkbox1" name="options[]" value="1">
	<label for="checkbox1"></label>
</span>

django-app-working-with-modal-forms/django_project/modal/templates/modal/snippets/custom-checkbox-header.html
<span class="custom-checkbox">
	<input type="checkbox" id="selectAll">
	<label for="selectAll"></label>
</span>

django-app-working-with-modal-forms/django_project/modal/templates/modal/snippets/modal-add.html
<!-- Edit Modal HTML -->
<div id="addEmployeeModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<form>
				<div class="modal-header">						
					<h4 class="modal-title">Add Employee</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">					
					<div class="form-group">
						<label>First Name</label>
						<input type="text" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Last Name</label>
						<input type="text" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" class="form-control" required>
					</div>
				</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<input type="submit" class="btn btn-success" value="Add">
				</div>
			</form>
		</div>
	</div>
</div>

django-app-working-with-modal-forms/django_project/modal/templates/modal/snippets/modal-delete.html
<!-- Delete Modal HTML -->
<div id="deleteEmployeeModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<form>
				<div class="modal-header">						
					<h4 class="modal-title">Delete Employee</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">					
					<p>Are you sure you want to delete these Records?</p>
					<p class="text-warning"><small>This action cannot be undone.</small></p>
				</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<input type="submit" class="btn btn-danger" value="Delete">
				</div>
			</form>
		</div>
	</div>
</div>

django-app-working-with-modal-forms/django_project/modal/templates/modal/snippets/modal-edit.html
<!-- Edit Modal HTML -->
<div id="editEmployeeModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<form>
				<div class="modal-header">						
					<h4 class="modal-title">Edit Employee</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">					
					<div class="form-group">
						<label>First Name</label>
						<input type="text" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Last Name</label>
						<input type="text" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" class="form-control" required>
					</div>
				</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<input type="submit" class="btn btn-info" value="Save">
				</div>
			</form>
		</div>
	</div>
</div>

django-app-working-with-modal-forms/django_project/modal/templates/modal/snippets/pagination.html
<div class="clearfix">
    <div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
    <ul class="pagination">
        <li class="page-item disabled"><a href="#">Previous</a></li>
        <li class="page-item"><a href="#" class="page-link">1</a></li>
        <li class="page-item"><a href="#" class="page-link">2</a></li>
        <li class="page-item active"><a href="#" class="page-link">3</a></li>
        <li class="page-item"><a href="#" class="page-link">4</a></li>
        <li class="page-item"><a href="#" class="page-link">5</a></li>
        <li class="page-item"><a href="#" class="page-link">Next</a></li>
    </ul>
</div>

django-app-working-with-modal-forms/django_project/modal/templates/modal/snippets/table-title.html
<div class="table-title">
	<div class="row">
		<div class="col-sm-6">
			<h2>Manage <b>Employees</b></h2>
		</div>
		
		<div class="col-sm-6">
			<a href="#addEmployeeModal" class="btn btn-success" data-toggle="modal">
				<i class="material-icons">&#xE147;</i> <span>Add New Employee</span>
			</a>
			<a href="#deleteEmployeeModal" class="btn btn-danger" data-toggle="modal">
				<i class="material-icons">&#xE15C;</i> <span>Delete</span>
			</a>						
		</div>
	</div>
</div>

django-app-working-with-modal-forms/django_project/modal/templates/modal/update.html
{% extends 'base.html' %}


{% block content %}
	<form method="post">{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Update">
	</form>
{% endblock %}