django-app-working-with-model-forms/django_project/myapp/models.py
from django.db import models


class Reporter(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return self.first_name

class Article(models.Model):
    headline = models.CharField(max_length=50)
    content = models.CharField(max_length=200)
    pub_date = models.DateField()
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)

    def __str__(self):
        return self.headline

django-app-working-with-model-forms/django_project/myapp/forms.py
from django.forms import ModelForm

from .models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['headline', 'content', 'reporter']

django-app-working-with-model-forms/django_project/myapp/views.py
from django.views import generic
from django.shortcuts import render
from django.urls import reverse_lazy

from .models import Article, Reporter
from .forms import ArticleForm


class HomeListView(generic.ListView):
    model = Reporter
    template_name = 'myapp/home.html'


class CreateReporterView(generic.CreateView):
    model = Reporter
    fields = ['first_name']
    template_name = 'myapp/create.html'
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('home')


class UpdateReporterView(generic.UpdateView):
    model = Reporter
    fields = ['first_name']
    template_name = 'myapp/update.html'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('home')


class DeleteReporterView(generic.DeleteView):
    model =  Reporter
    template_name = 'myapp/delete.html'
    template_name_suffix = '_check_delete'
    success_url = reverse_lazy('home')

django-app-working-with-model-forms/django_project/myapp/templates/myapp/create.html
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Add">
</form>

django-app-working-with-model-forms/django_project/myapp/templates/myapp/delete.html
<p><strong>Are you sure you want to delete {{object}}?</strong></p>
<form action="" method="post">
  {% csrf_token %}
  <a href="{% url 'home' %}">Cancel</a>
  <input type="submit" value="Delete">
</form>

django-app-working-with-model-forms/django_project/myapp/templates/myapp/home.html
<a href="{% url 'create' %}">Add Reporter</a>
{% if reporter_list %}
  <ul>
    {% for reporter in reporter_list %}
      <li>
        {{reporter}} -
        <a href="{% url 'update' reporter.id %}">Update</a> -
        <a href="{% url 'delete' reporter.id %}">Delete</a>
      </li>
    {% endfor %}
  </ul>
{% else %}
<p><strong>No available reporters.</strong></p>
{% endif %}

django-app-working-with-model-forms/django_project/myapp/templates/myapp/update.html
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Update">
</form>